name = "Saga of the Sunless Sky"
author = "Jim9222"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0365ed85b632095cc96090df72bf56bb867bc6135c8e94805624793e6c75914d"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
