name = "Saga of the Sunless Sky"
author = "Jim9222"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93149d18a094a3cbc57aad5a9a0e26eeabbf648bb41869af8a0eea241d404fae"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
