name = "Twilight of Asgard"
author = "Jim9222"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21f9332301a62005567df3d6f10e3ec10b5c054d71e214de1be3e641cc9cd792"

[versions]
fabric = "0.15.7"
minecraft = "1.20.2"
